{% extends "template/open.phtml" %}
{% block content %}
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        {% for f in featured %}
        <div class="item {{selectedFeaturedId == f.getId() ? 'active':''}}">
            <img data-src="" src="{{ url('img' ~ f.getImage()) }}" alt="{{ f.getTitle() }}">
            <div class="container">
                <div class="carousel-caption">
                    <h3 class="hidden-xs">{{ f.getTitle() }}</h3>
                    <h5 class="visible-xs">{{ f.getTitle() }}</h5>
                    <p class="hidden-xs">{{ f.getSubtitle() }}</p>
                    <h6 class="visible-xs">{{ f.getSubtitle() }}</h6>
                    {% if f.getLink() != '' %}
                    <p><a class="btn btn-lg btn-primary" href="{{f.getLink()}}" role="button">Saiba Mais &raquo;</a></p>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
</div><!-- /.carousel -->



<!-- Marketing messaging and featurettes
================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->

<div class="container" style="text-align:center;">

    <!-- Three columns of text below the carousel -->
    <div class="row">
        <div class="col-lg-4">
            <img class="img-circle" src="{{ url('img/layout/pizza-icon.png') }}" alt="Image">
            <h2>Cardápio</h2>
            <p>Conheça todas as nossas pizzas</p>
            <p><a class="btn btn-default" href="{{ url('menu') }}" role="button">Ver Mais &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
            <img class="img-circle"src="{{ url('img/layout/dollar-icon.png') }}" alt="Generic placeholder image">
            <h2>Promoções</h2>
            <p>Fique por dentro das nossas promoções</p>
            <p><a class="btn btn-default" href="{{ url('deals') }}" role="button">Ver Mais &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
            <img class="img-circle"src="{{ url('img/layout/map-icon.png') }}" alt="Generic placeholder image">
            <h2>Localização</h2>
            <p>Saiba como encontrar a pizzaria</p>
            <p><a class="btn btn-default" href="{{ url('map') }}" role="button">Ver Mais &raquo;</a></p>
        </div>
    </div>

</div><!-- /.container -->
{% endblock %}