<!DOCTYPE html>
<html lang="en">
    <head>
        {% block head %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>{{ _company.getName() }} | {{ title }}</title>

        <!-- Bootstrap core CSS -->
        <!-- Custom styles for this template -->

        <link href="{{ url("css/bootstrap.css") }}" rel="stylesheet" />

        <link href="{{ url("css/carousel.css") }}" rel="stylesheet" />
        <link href="{{ url("css/customizations.css") }}" rel="stylesheet" />
        <link href="{{ url('css/jquery.timepicker.css') }}" rel="stylesheet">
        <link href="{{ url('css/datepicker.css') }}" rel="stylesheet">

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->

        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="{{ url('js/jquery-1.10.2.min.js') }}"></script>
        <script src="{{ url('js/bootstrap.min.js') }}"></script>
        <script src="{{ url('js/holder.js') }}"></script>
        <script src="{{ url('js/bootstrap-tagsinput.min.js') }}"></script>
        <script src="{{ url('js/jquery.timepicker.min.js') }}"></script>
        <script src="{{ url('js/bootstrap-datepicker.js') }}"></script>
        <script src="{{ url('js/jquery.scrollTo-min.js') }}"></script>

        {% endblock %}
    </head>
    <body>
        <div class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url('') }}">{{ _company.getName() }}</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a  href="{{ url('menu') }}">Cardápio</a></li>
                    <li><a href="{{ url('deals') }}">Promoções</a></li>
                    <li><a href="{{ url('map') }}">Localizaçao</a></li>
                    <li><a href="{{ url('contact') }}">Contato</a></li>
                    <li><a href="{{ url('static/aboutus') }}">Quem somos</a></li>
                </ul>
            </div>
        </div>

        <div class="container">
            {% block content %}
            {% endblock %}
        </div>

        <!-- FOOTER -->
        <footer class="bs-footer" style="background: #006742;clear: both">
            <hr class="" />
            <div class="container marketing">
                <div class="col-lg-4 text-center">
                    <img class="img-rounded" src="{{ url("img/layout/logo.gif") }}" alt="Generic placeholder image">
                </div>
                <div class="col-lg-4">
                    <p class="text-center">{{ _company.getAddress().getStreet() }}, {{ _company.getAddress().getNumber() }} 
                    <p class="text-center"> {{ _company.getAddress().getObservation() }}</p>
                    <p class="text-center">{{ _company.getAddress().getNeighborhood() }}</p>
                    <p class="text-center">{{ _company.getAddress().getCity().getName() }}, {{ _company.getAddress().getState().getCode() }} | CEP: {{ _company.getAddress().getStreetCode() }}</p>
                    <p class="text-center">{{ _company.getContact().getPhonesAsString() }}</p>
                </div> 
                <div class="col-lg-4 text-right">
                    <a href="#">Topo</a> <br />
                    <a href="{{ url('admin') }}">Administração</a>
                </div>
            </div>
        </footer>
        {% if _config.isProduction() %}
        <script>
        (function(i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function() {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                    m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-47303963-1', '{{_config['env']['host']}}');
        ga('send', 'pageview');

        </script>
        {% endif %}
    </body>
</html>