{% extends '../template/adm.phtml' %}
{% block content %}
<div class="row">
    <div class="col-md-3 ">
        <div class="bs-sidebar hidden-print" role="complementary">
            <ul class="nav bs-sidenav">
                <li>
                    <a href="{{ url(currentController) }}" class="list-group-item" ><span class="menu-icon glyphicon glyphicon-play"></span>Inicio</a>
                    <a href="{{ url(currentController ~ '/new') }}" class="list-group-item" ><span class="menu-icon glyphicon glyphicon-edit"></span>Novo</a>
                    <a href="{{ url(currentController) }}" class="list-group-item" ><span class="menu-icon glyphicon glyphicon-search"></span>Pesquisar</a>
                </li>
            </ul>
        </div>
    </div>
    <div class="col-md-9 main-content" role="main">
        {{ _session.getMessage() }}
        <div class="well">
            <fieldset>
                <legend>Pesquisar</legend>
                <form action="{{url(currentController ~ '/search')}}" method="get">
                    <div class="form-group">
                        <label for="search" >Nome</label>
                        <input type="text" class="form-control " name="search" value="<?= array_key_exists('search', $_GET) ? $_GET['search'] : ''; ?>" />
                    </div>
                    <div class="form-group" >
                        <label for="district" class="control-label" >Tipo</label>
                        <select class="form-control" name="type">
                            <option value="">---Selecione---</option>
                            {% for st in types %}
                            <option 
                                value="{{st.getId()}}" 
                                {{ selectedType != null and selectedType == st.getId() ? 'selected':'' }} 
                                    >{{st.getName()}}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="form-group">
                        <div class="col-lg-1 col-md-2 col-xs-12 col-lg-offset-9 col-md-offset-9">
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="active" {{active?'checked="checked"':''}} class="form-control"/>Ativos
                                </label>
                            </div>
                        </div>
                        <div class="col-lg-2 col-md-1 col-xs-12 text-right">
                            <button class="btn btn-primary" type="submit"><span class="menu-icon glyphicon glyphicon-search"></span></button>
                        </div>
                    </div>
                </form>
            </fieldset>
            <fieldset>
                <legend>Resultado</legend>
                <table class="table table-striped table-hover table-responsive">
                    <thead class="fixedthead" >
                        <tr>
                            <th class="col-xs-2 col-sm-1" >#</th>
                            <th class="col-xs-5 col-sm-7" >Nome</th>
                            <th class="col-xs-5 col-sm-4">Último update</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for u in results %}
                        <tr>
                            <td><a href="{{ url(currentController ~ '/view/' ~ u.getId()) }}"><span class=" glyphicon glyphicon-edit "></span></a></td>
                            <td>{{ u.getName() }}</td>
                            <td>{{ formatDate(u.getLastUpdate())}}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {{ pagination }}
            </fieldset>
        </div>

    </div>
</div>
{% endblock %}