{% extends '../template/adm.phtml' %}
{% block content %}
<div class="row">
    <div class="col-md-3 ">
        <div class="bs-sidebar hidden-print" role="complementary">
            <ul class="nav bs-sidenav">
                <li>
                    <a href="{{ url(currentController) }}" class="list-group-item" ><span class="menu-icon glyphicon glyphicon-play"></span>Inicio</a>
                    <a href="{{ url(currentController ~ '/new') }}" class="list-group-item" ><span class="menu-icon glyphicon glyphicon-edit"></span>Novo</a>
                    <a href="{{ url(currentController) }}" class="list-group-item" ><span class="menu-icon glyphicon glyphicon-search"></span>Pesquisar</a>
                </li>
            </ul>
        </div>
    </div>
    <div class="col-md-9 main-content" role="main">
        {{ _session.getMessage() }}
        <div class="well">
            <fieldset>
                <legend>Dados</legend>
                <form action="{{ url(currentController ~ '/save/') }}" method="post">
                    <input type="hidden" name="id" value="{{instance.getId()}}">
                    <div class="form-group">
                        <label for="name" >Nome</label>

                        <input 
                            type="text" 
                            class="form-control" 
                            name="name" 
                            placeholder="{{instance.getName()}}" 
                            value="{{instance.getName()}}" />
                    </div>

                    <div class="form-group">
                        <label for="description" >Description</label>
                        <input 
                            type="text" 
                            class="form-control" 
                            name="description" 
                            value="{{instance.getDescription()}}"
                            placeholder="{{instance.getDescription()}}" />
                    </div>

                    <div class="form-group" >
                        <label for="type_id" class="control-label" >Tipo</label>
                        <select class="form-control" name="type_id">
                            <option value="">---Selecione---</option>
                            {% for st in types %}
                            <option value="{{st.getId()}}" {{ instance.getType() != null and instance.getType().getId() == st.getId() ? 'selected' : '' }} >{{st.getName()}}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="form-group">
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" 
                                       name="active" {{instance.getActive()?'checked="checked"':''}} 
                                       class="form-control" />Ativo?
                            </label>
                        </div>
                    </div>
                    <div class="form-group text-right" >
                        <a class="btn btn-danger" href="{{url(currentController)}}"  >Cancelar<span class="menu-icon glyphicon glyphicon-ban-circle"></span></a>
                        <button type="submit" class="btn btn-success"  >Salvar<span class="menu-icon glyphicon glyphicon-ok"></span></button>
                    </div>
                </form>
            </fieldset>
        </div>
    </div>
</div> 
{% endblock %}