{% extends "template/open.phtml" %}
{% block content %}
{{_session.getMessage()}}
<h2>Contato</h2>
<p class="text-justify">Para nos contactar você pode utilizar o seguinte formunlário ou, se desejar, utilize o telefone disonível no rodapé da página.</p>
<form role="form" action="{{ url('contact/send') }}" method="post">
    <div class="form-group">
        <label for="email">Email</label>
        <input type="email" class="form-control" name="email" value="{{instance.getEmail()}}" placeholder="exemplo@email.com">
    </div>
    <div class="form-group">
        <label for="email">Nome</label>
        <input type="text" class="form-control" name="name" value="{{instance.getName()}}"  placeholder="Meu Nome">
    </div>
    <div class="form-group">
        <label for="mensagem">Mensagem</label>
        <textarea class="form-control" id="mensagem" name="mensagem" >{{message}}</textarea>
    </div>
    <div class="form-group">
        <label for="gender">Sexo</label>
        <select class="form-control" id="gender" name="gender" >
            <option value="">---Selecione---</option>
            <option value="M" {{instance.getGender() == 'M' ? 'selected':''}}>Masculino</option>
            <option value="F" {{instance.getGender() == 'F' ? 'selected':''}}>Feminino</option>
        </select>
    </div>
    <div class="form-group">
        <div class="checkbox">
            <label>
                <input type="checkbox" name="receive_news" {{instance.getReceiveNews() ? 'checked' : ''}}> Receber atualizações
            </label>
        </div>
    </div>
    <button type="submit" class="btn btn-default">Enviar</button>
</form>
{% endblock %}