{% extends '../template/adm.phtml' %}
{% block content %}
<div class="row">
    <div class="col-md-3 ">
        <div class="bs-sidebar hidden-print" role="complementary">
            <ul class="nav bs-sidenav">
                <li>
                    <a href="{{ url(currentController) }}" class="list-group-item" ><span class="menu-icon glyphicon glyphicon-play"></span>Inicio</a>
                    <a href="{{ url(currentController ~ '/new') }}" class="list-group-item" ><span class="menu-icon glyphicon glyphicon-edit"></span>Novo</a>
                    <a href="{{ url(currentController) }}" class="list-group-item" ><span class="menu-icon glyphicon glyphicon-search"></span>Pesquisar</a>
                </li>
            </ul>
        </div>
    </div>
    <div class="col-md-9 main-content" role="main">
        {{ _session.getMessage() }}
        <div class="well">
            <fieldset>
                <legend>Dados</legend>
                <form action="{{ url(currentController ~ 'save/') }}" method="post">
                    <input type="hidden" name="id" value="{{instance.getId()}}">
                    <div class="form-group">
                        <label for="name" >Nome</label>
                        <input type="text" class="form-control" name="name" required placeholder="{{instance.getName()}}" value="{{instance.getName()}}"/>
                    </div>
                    <div class="form-group">
                        <label for="email" >Email</label>
                        <input type="email" class="form-control" name="email" required placeholder="{{instance.getEmail()}}"  value="{{instance.getEmail()}}"/>
                    </div>
                    <div class="form-group">
                        <label for="cpf" >CPF</label>
                        <input type="text" class="form-control" name="cpf" required placeholder="{{instance.getCpf()}}" value="{{instance.getCpf()}}"/>
                    </div>
                    <div class="form-group">
                        <label for="passwd1" >Senha (6 caracteres)</label>
                        <input type="password" class="form-control" {{ instance.getId() is empty ? "required":"" }} name="passwd1" />
                    </div>
                    <div class="form-group">
                        <label for="passwd2" >Confirme a senha</label>
                        <input  type="password" class="form-control" {{ instance.getId() is empty ? "required":"" }} name="passwd2" />
                    </div>

                    <div class="form-group">
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" name="active" {{instance.getActive()?'checked="checked"':''}} class="form-control"/>Ativo?
                            </label>
                        </div>
                    </div>
                    <div class="form-group text-right" >
                        <a class="btn btn-danger" href="{{url(currentController)}}"  >Cancelar<span class="menu-icon glyphicon glyphicon-ban-circle"></span></a>
                        <button type="submit" class="btn btn-success"  >Salvar<span class="menu-icon glyphicon glyphicon-ok"></span></button>
                    </div>
                </form>
            </fieldset>
        </div>
    </div>
</div> 
{% endblock %}