{% extends '../template/adm.phtml' %}
{% block content %}
<div class="row">
    <div class="col-md-3 ">
        <div class="bs-sidebar hidden-print" role="complementary">
            <ul class="nav bs-sidenav">
                <li>
                    <a href="{{ url(currentController) }}" class="list-group-item" ><span class="menu-icon glyphicon glyphicon-play"></span>Inicio</a>
                    <a href="{{ url(currentController ~ '/new') }}" class="list-group-item" ><span class="menu-icon glyphicon glyphicon-edit"></span>Novo</a>
                    <a href="{{ url(currentController) }}" class="list-group-item" ><span class="menu-icon glyphicon glyphicon-search"></span>Pesquisar</a>
                </li>
            </ul>
        </div>
    </div>
    <div class="col-md-9 main-content" role="main">
        {{ _session.getMessage() }}
        <div class="well">
            <fieldset>
                <legend>Dados</legend>
                <form action="{{ url(currentController ~ '/save/') }}" method="post">
                    <input type="hidden" name="id" value="{{instance.getId()}}">
                    <div class="form-group">
                        <label for="name" >Nome <span class="text-danger">*</span></label>
                        <input type="text" class="form-control" name="name" required placeholder="{{instance.getName()}}" value="{{instance.getName()}}"/>
                    </div>
                    <div class="form-group">
                        <label for="name" >Descrição <span class="text-danger">*</span></label>
                        <textarea class="form-control" name="description" >{{instance.getDescription()}}</textarea>
                    </div>
                    <div class="form-inline row">
                        <div class="form-group col-lg-6 col-md-6 col-xs-12 col-sm-6">
                            <label class="control-label">Data inicial</label>
                            <div class="input-date input-group date" data-date-format="dd/mm/yy" data-date="{{ formatDate( instance.getStartDateRange() ,'only-day') }}">
                                <span class="input-group-btn add-on">
                                    <button class="btn btn-primary">
                                        <span class="glyphicon glyphicon-calendar icon-calendar"></span>
                                    </button>
                                </span>
                                <input type="text" class="form-control" name="startDate" value="{{ formatDate( instance.getStartDateRange() ,'only-day') }}"  >
                            </div>
                        </div>
                        <div class="form-group col-lg-6 col-md-6 col-xs-12 col-sm-6">
                            <label class="control-label">Data final</label>
                            <div class="input-date input-group date" data-date-format="dd/mm/yy" data-date="{{ formatDate( instance.getEndDateRange() ,'only-day') }}">
                                <span class="input-group-btn add-on">
                                    <button class="btn btn-primary">
                                        <span class="glyphicon glyphicon-calendar icon-calendar"></span>
                                    </button>
                                </span>
                                <input type="text" class="form-control" name="endDate" value="{{ formatDate( instance.getEndDateRange() ,'only-day') }}"  >
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" name="active" {{instance.getActive()?'checked="checked"':''}} class="form-control"/>Ativo?
                            </label>
                        </div>
                    </div>
                    <div class="form-group text-right" >
                        <a class="btn btn-danger" href="{{url(currentController)}}"  >Cancelar<span class="menu-icon glyphicon glyphicon-ban-circle"></span></a>
                        <button type="submit" class="btn btn-success"  >Salvar<span class="menu-icon glyphicon glyphicon-ok"></span></button>
                    </div>
                </form>
            </fieldset>
        </div>
    </div>
</div> 
{% endblock %}