{% extends "template/open.phtml" %}
{% block content %}
<h2>Promoções</h2>
<hr />
{% for d in deals %}
<div class="text-justify">
    <h3>{{d.getName()}}</h3>
    {{ d.getDescription() }}
    {% if d.getStartDateRange() is not empty or d.getEndDateRange() is not empty %}
    <p class="text-right text-warning">Válido 
        {{ d.getStartDateRange() is empty ? '' : 'apartir de  ' ~ formatDate(d.getStartDateRange(), 'only-day')  }}
        {{ d.getEndDateRange() is empty ? '' : ' até ' ~ formatDate(d.getEndDateRange(), 'only-day')  }}
    </p>
</div>
{% endif %}
{% endfor %}
{% if count(deals) == 0 %}
<p class="text-warning">Não temos nenhuma promoção ativa no momento.</p>
{% endif %}
{% endblock %}