{% extends "template/open.phtml" %}
{% block content %}
<h2>Promoções</h2>
<hr />
{% for d in deals %}
<div class="text-justify">
    <h3>{{d.getName()}}</h3>
    {{ d.getDescription() }}
    {% if d.getStartDateRange() != null or d.getEndDateRange() != null  %}
    <p class="text-right text-warning">Válida 
        {{ d.getStartDateRange() == null ? '' : 'apartir de  ' ~ formatDate(d.getStartDateRange(), 'only-day')  }}
        {{ d.getEndDateRange() == null ? '' : ' até ' ~ formatDate(d.getEndDateRange(), 'only-day')  }}
    </p>
    {% endif %}
</div>
{% endfor %}
{% if count(deals) == 0 %}
<p class="text-warning">Não temos nenhuma promoção ativa no momento.</p>
{% endif %}
{% endblock %}