{% extends 'template/adm.phtml' %}
{% block content %}
<div class="container bs-docs-container">
    <div class="row">
        <div class="col-md-3 ">
            <div class="bs-sidebar hidden-print"  data-spy="affix" data-offset-bottom="180" role="complementary">
                <ul class="nav bs-sidenav">
                    <li>
                        <a href="{{ url('usercrud/edit') }}" class="list-group-item" ><span class="menu-icon glyphicon glyphicon-edit"></span>Novo</a>
                        <a href="{{ url('usercrud') }}" class="list-group-item" ><span class="menu-icon glyphicon glyphicon-edit"></span>Pesquisar</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-md-9" role="main">
            <p><?php $this->flashSession->output() ?></ p>
            <form action="{{ url('usercrud/edit/'~user.getId()) }}" method="post">
                <input type="hidden" name="id" value="{{user.getId()}}">
                <div class="form-group">
                    <label for="name" >Nome</label>
                    <input type="text" class="form-control" name="name" required placeholder="Meu Nome" value="{{user.getName()}}"/>
                </div>
                <div class="form-group">
                    <label for="email" >Email</label>
                    <input type="email" class="form-control" name="email" required placeholder="email@exemplo.com"  value="{{user.getEmail()}}"/>
                </div>
                <div class="form-group">
                    <label for="cpf" >CPF</label>
                    <input type="text" class="form-control" name="cpf" required placeholder="00000000000" value="{{user.getCpf()}}"/>
                </div>
                <div class="form-group">
                    <label for="passwd1" >Senha (6 caracteres)</label>
                    <input type="password" class="form-control" required name="passwd1" placeholder="*******" />
                </div>
                <div class="form-group">
                    <label for="passwd2" >Confirme a senha</label>
                    <input  type="password" class="form-control" required name="passwd2" placeholder="*******"/>
                </div>

                <div class="form-group text-right" >
                    <a class="btn btn-danger" href="{{url('usercrud')}}"  >Cancelar<span class="menu-icon glyphicon glyphicon-ban-circle"></span></a>
                    <button type="submit" class="btn btn-success"  >Salvar<span class="menu-icon glyphicon glyphicon-ok"></span></button>
                </div>
            </form>
        </div>
    </div> 
</div>
{% endblock %}