{% extends 'template/adm.phtml' %}
{% block content %}
<div class="container bs-docs-container">
    <div class="row">
        <div class="col-md-3 ">
            <div class="bs-sidebar hidden-print"  data-spy="affix" data-offset-bottom="180" role="complementary">
                <ul class="nav bs-sidenav">
                    <li>
                        <a href="{{ url('usercrud/view') }}" class="list-group-item" ><span class="menu-icon glyphicon glyphicon-edit"></span>Novo</a>
                        <a href="{{ url('usercrud') }}" class="list-group-item" ><span class="menu-icon glyphicon glyphicon-edit"></span>Pesquisar</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-md-9" role="main">
            <form action="{{url('usercrud')}}" method="post">
                <div class="input-group">
                    <input type="text" class="form-control" name="search" />
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit"><span class="menu-icon glyphicon glyphicon-search"></span></button>
                    </span>
                </div>
            </form>
            <ul class="pagination">
                <li class="disabled"><a href="#" >&laquo;</a></li>
                <li class="active"><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li><a href="#">&raquo;</a></li>
            </ul>
            <div class="table-responsive">

                <table class="table table-striped table-hover">
                    <thead class="fixedthead" >
                        <tr>
                            <th class="col-xs-2 col-sm-1" >#</th>
                            <th class="col-xs-4 col-sm-3" >Nome</th>
                            <th class="col-xs-6 col-sm-4" >Email</th>
                            <th class="hidden-xs col-sm-4">Último acesso</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><a href="#"><span class=" glyphicon glyphicon-edit "></span></a></td>
                            <td>Luis Boch</td>
                            <td>luis.c.boch@gmail.com</td>
                            <td class="hidden-xs ">Dez, 25 de 2013</td>
                        </tr>
                        <tr>
                            <td><a href="#"><span class=" glyphicon glyphicon-edit "></span></a></td>
                            <td>Luis Boch</td>
                            <td>luis.c.boch@gmail.com</td>
                            <td class="hidden-xs ">Dez, 25 de 2013</td>
                        </tr>
                        <tr>
                            <td><a href="#"><span class=" glyphicon glyphicon-edit "></span></a></td>
                            <td>Luis Boch</td>
                            <td>luis.c.boch@gmail.com</td>
                            <td class="hidden-xs ">Dez, 25 de 2013</td>
                        </tr>
                        <tr>
                            <td><a href="#"><span class=" glyphicon glyphicon-edit "></span></a></td>
                            <td>Luis Boch</td>
                            <td>luis.c.boch@gmail.com</td>
                            <td class="hidden-xs ">Dez, 25 de 2013</td>
                        </tr>
                        <tr>
                            <td><a href="#"><span class=" glyphicon glyphicon-edit "></span></a></td>
                            <td>Luis Boch</td>
                            <td>luis.c.boch@gmail.com</td>
                            <td class="hidden-xs ">Dez, 25 de 2013</td>
                        </tr>
                        <tr>
                            <td><a href="#"><span class=" glyphicon glyphicon-edit "></span></a></td>
                            <td>Luis Boch</td>
                            <td>luis.c.boch@gmail.com</td>
                            <td class="hidden-xs ">Dez, 25 de 2013</td>
                        </tr>
                        <tr>
                            <td><a href="#"><span class=" glyphicon glyphicon-edit "></span></a></td>
                            <td>Luis Boch</td>
                            <td>luis.c.boch@gmail.com</td>
                            <td class="hidden-xs ">Dez, 25 de 2013</td>
                        </tr>
                        <tr>
                            <td><a href="#"><span class=" glyphicon glyphicon-edit "></span></a></td>
                            <td>Luis Boch</td>
                            <td>luis.c.boch@gmail.com</td>
                            <td class="hidden-xs ">Dez, 25 de 2013</td>
                        </tr>
                        <tr>
                            <td><a href="#"><span class=" glyphicon glyphicon-edit "></span></a></td>
                            <td>Luis Boch</td>
                            <td>luis.c.boch@gmail.com</td>
                            <td class="hidden-xs ">Dez, 25 de 2013</td>
                        </tr>
                        <tr>
                            <td><a href="#"><span class=" glyphicon glyphicon-edit "></span></a></td>
                            <td>Luis Boch</td>
                            <td>luis.c.boch@gmail.com</td>
                            <td class="hidden-xs ">Dez, 25 de 2013</td>
                        </tr>
                        <tr>
                            <td><a href="#"><span class=" glyphicon glyphicon-edit "></span></a></td>
                            <td>Luis Boch</td>
                            <td>luis.c.boch@gmail.com</td>
                            <td class="hidden-xs ">Dez, 25 de 2013</td>
                        </tr>
                        <tr>
                            <td><a href="#"><span class=" glyphicon glyphicon-edit "></span></a></td>
                            <td>Luis Boch</td>
                            <td>luis.c.boch@gmail.com</td>
                            <td class="hidden-xs ">Dez, 25 de 2013</td>
                        </tr>
                        <tr>
                            <td><a href="#"><span class=" glyphicon glyphicon-edit "></span></a></td>
                            <td>Luis Boch</td>
                            <td>luis.c.boch@gmail.com</td>
                            <td class="hidden-xs ">Dez, 25 de 2013</td>
                        </tr>
                        <tr>
                            <td><a href="#"><span class=" glyphicon glyphicon-edit "></span></a></td>
                            <td>Luis Boch</td>
                            <td>luis.c.boch@gmail.com</td>
                            <td class="hidden-xs ">Dez, 25 de 2013</td>
                        </tr>
                        <tr>
                            <td><a href="#"><span class=" glyphicon glyphicon-edit "></span></a></td>
                            <td>Luis Boch</td>
                            <td>luis.c.boch@gmail.com</td>
                            <td class="hidden-xs ">Dez, 25 de 2013</td>
                        </tr>
                        <tr>
                            <td><a href="#"><span class=" glyphicon glyphicon-edit "></span></a></td>
                            <td>Luis Boch</td>
                            <td>luis.c.boch@gmail.com</td>
                            <td class="hidden-xs ">Dez, 25 de 2013</td>
                        </tr>
                        <tr>
                            <td><a href="#"><span class=" glyphicon glyphicon-edit "></span></a></td>
                            <td>Luis Boch</td>
                            <td>luis.c.boch@gmail.com</td>
                            <td class="hidden-xs ">Dez, 25 de 2013</td>
                        </tr>
                        <tr>
                            <td><a href="#"><span class=" glyphicon glyphicon-edit "></span></a></td>
                            <td>Luis Boch</td>
                            <td>luis.c.boch@gmail.com</td>
                            <td class="hidden-xs ">Dez, 25 de 2013</td>
                        </tr>
                        <tr>
                            <td><a href="#"><span class=" glyphicon glyphicon-edit "></span></a></td>
                            <td>Luis Boch</td>
                            <td>luis.c.boch@gmail.com</td>
                            <td class="hidden-xs ">Dez, 25 de 2013</td>
                        </tr>
                        <tr>
                            <td><a href="#"><span class=" glyphicon glyphicon-edit "></span></a></td>
                            <td>Luis Boch</td>
                            <td>luis.c.boch@gmail.com</td>
                            <td class="hidden-xs ">Dez, 25 de 2013</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <ul class="pagination">
                <li class="disabled"><a href="#" >&laquo;</a></li>
                <li class="active"><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li><a href="#">&raquo;</a></li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}