{% extends 'template/open.phtml' %}
{% block content %}
<div class="row">

    <div class="col-md-3 ">
        <span style="height: 20px;display:block;"></span>
        <div class="bs-sidebar hidden-print" role="complementary">
            <ul class="nav bs-sidenav">
                <li>
                    {% for t in types %}
                    {% if count(t.getItens()) !=  0 %}
                    <a href="#type{{ t.getId() }}"
                       class="list-group-item">{{ t.getName() }}</a>
                    {% endif %}
                    {% endfor %}
                </li>
            </ul>
        </div>
    </div>
    <div class="col-md-9 main-content" role="main">
        {{ _session.getMessage() }}
        <div class="well">
            {% for t in types %}
            {% if t.getId() != _config['env']['portions_id'] %}
            {% if count(t.getItens()) !=  0 %}
            <a id="type{{t.getId()}}" style="display: block;height: 50px;width: 10px"></a>
            <fieldset>
                <legend  >{{ t.getName() }}</legend>
                <div class="row">
                    {% for p in ctrl.getItens(t) %}
                    {% if p.getActive() %}
                    <div class="container col-lg-4" style="height: 150px;">
                        <h4>{{p.getName()}}</h4>
                        <p class="text-justify help-block">{{p.getDescription()}}</p>
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>
            </fieldset>
            {% endif %}
            {% endif %}
            {% if t.getId() == _config['env']['portions_id'] %}
            {% if count(t.getItens()) !=  0 %}
            <a id="type{{t.getId()}}" style="display: block;height: 50px;width: 10px"></a>
            <fieldset>
                <legend  >{{ t.getName() }}</legend>
                <div class="row">
                    <?
                    $html = "";
                    $itens  = $ctrl->getItens($t);
                    for ($i = 0; $i < count($itens); $i++) {
                        if($i > 0){
                            $html.=', ';
                        }
                        
                        $html .= $itens[$i]->getName();
                    }
                    ?>
                    <div style="padding: 0px 15px">
                        <p class="text-justify help-block"><?=$html?></p>
                    </div>
                </div>
            </fieldset>
            {% endif %}
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div> 
<script type="text/javascript">

    setTimeout(function() {
        var $sideBar = $('.bs-sidebar');
        $sideBar.affix({
            offset: {
                top: function() {
                    var offsetTop = $sideBar.offset().top;
                    var sideBarMargin = parseInt($sideBar.children(0).css('margin-top'), 10);
                    var navOuterHeight = $('#navbar').outerHeight(true) + 18;
                    return (this.top = offsetTop - navOuterHeight - sideBarMargin);
                }
                , bottom: function() {
                    return (this.bottom = $('.bs-footer').outerHeight(true));
                }
            }
        });
    }, 100);
</script>
{% endblock %}
