{% extends "template/open.phtml" %}
{% block content %}
<h2>Cardápio</h2>
<hr />
<div class="row">
    {% for t in types %}
    {% if count(t.getItens()) !=  0 %}
    <div class="col-lg-4">
        <a href="{{ url('menu/all#type' ~ t.getId()) }}" class=""><div class="well">{{ t.getName() }}<div class="pull-right"><span class="menu-icon glyphicon glyphicon-play"></span></div></div></a>
    </div>
    {% endif %}
    {% endfor %}
</div>
{% endblock %}